[package]
name = "cosmic-classic-menu"
version = "0.0.1"
edition = "2021"

[dependencies]
rust-embed = "8.0.0"
tokio = "1.31"
serde = "1.0.210"
freedesktop-desktop-entry = "0.7.7"
current_locale = "0.1.1"
logind-zbus = "5.1.0"
zbus = "5.3.1"
rustix = "0.38.44"
i18n-embed = { version = "0.14.1", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.8"
once_cell = "1.20.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-log = "0.2.0"
serde_json = "1.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["applet", "wayland", "tokio", "desktop", "desktop-systemd-scope"]

[package.metadata.deb]
maintainer = "Kamil Lihan <k.lihan@outlook.com>"
copyright = "2025, Kamil Lihan <k.lihan@outlook.com>"
license-file = ["LICENSE", "4"]
extended-description = """\
A menu applet for COSMIC Desktop."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    # both syntaxes are equivalent:
    ["target/release/cosmic-classic-menu", "usr/bin/", "755"],
    { source = "README.md", dest = "usr/share/doc/cosmic-classic-menu/README", mode = "644"},
    { source = "data/icons/com.championpeak87.cosmic-classic-menu.svg", dest = "usr/share/pixmaps/com.championpeak87.cosmic-classic-menu.svg", mode = "644"},
    { source = "data/com.championpeak87.cosmic-classic-menu.desktop", dest = "usr/share/applications/com.championpeak87.cosmic-classic-menu.desktop", mode = "644"},
]

[features]
xdg-portal = ["libcosmic/xdg-portal"]
rfd = ["libcosmic/rfd"]
default = ["xdg-portal"]
