[package]
name = "cosmic-classic-menu"
version = "0.0.1"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
rust-embed = "8.0.0"
tokio = "1.31"
serde = "1.0.210"
url = "2.4.0"
regex = "1.11.1"
freedesktop-desktop-entry = "0.7.7"
libc = "0.2.169"
futures = "0.3.21"
tracing = "0.1"
pop-launcher = { git = "https://github.com/pop-os/launcher/" }
pop-launcher-service = { git = "https://github.com/pop-os/launcher/" }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["applet", "wayland", "tokio", "desktop", "desktop-systemd-scope"]

[features]
xdg-portal = ["libcosmic/xdg-portal"]
rfd = ["libcosmic/rfd"]
default = ["xdg-portal"]
